package UI.BlueAlliance;

import javax.swing.JLabel;

/**
 * This acts as a container for the Driver Station and Robot communication
 * indicators - mostly for visual appeal.
 *
 * Complete System developed by:
 *
 * @author Alex Bassett
 * @author Walton Robotics - Team 2974
 * @author Foundation code developed by Josh, Andrew Lobos, Team 225
 * @author Structural assistance and refactoring by Doug Neumann
 */
public class BlueCommStatus extends javax.swing.JPanel {

    /**
     * Creates a new BlueCommStatus
     */
    public BlueCommStatus() {
        initComponents();
    }

    /**
     * Gets the Driver Station communication indicator.
     *
     * @return A JLabel acting as the DS communication indicator.
     */
    public JLabel getDS() {
        return dsIndic;
    }

    /**
     * Gets the Robot communication indicator.
     *
     * @return A JLabel acting as the robot communication indicator.
     */
    public JLabel getRob() {
        return robotIndic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        robotIndic = new javax.swing.JLabel();
        dsIndic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        setMaximumSize(new java.awt.Dimension(60, 53));
        setMinimumSize(new java.awt.Dimension(60, 53));
        setPreferredSize(new java.awt.Dimension(60, 53));

        robotIndic.setBackground(new java.awt.Color(153, 153, 153));
        robotIndic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        robotIndic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        robotIndic.setText("ROBOT");
        robotIndic.setOpaque(true);

        dsIndic.setBackground(new java.awt.Color(153, 153, 153));
        dsIndic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dsIndic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dsIndic.setText("DS");
        dsIndic.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(robotIndic, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(dsIndic, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(robotIndic, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(dsIndic, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dsIndic;
    private javax.swing.JLabel robotIndic;
    // End of variables declaration//GEN-END:variables
}
