package UI.BlueAlliance;

import OFMS.FieldAndRobots;
import javax.swing.JLabel;

/**
 * This acts as a container class for 3 team UI containers and an "alliance
 * ready" indicator.
 *
 * Complete System developed by:
 *
 * @author Alex Bassett
 * @author Walton Robotics - Team 2974
 * @author Foundation code developed by Josh, Andrew Lobos, Team 225
 * @author Structural assistance and refactoring by Doug Neumann
 */
public class BlueAlli extends javax.swing.JPanel {

    /**
     * Creates a new BlueAlli
     */
    public BlueAlli() {
        initComponents();
        blue_UI_Block1.getTeamIndic().setText("0001");
        blue_UI_Block2.getTeamIndic().setText("0002");
        blue_UI_Block3.getTeamIndic().setText("0003");
        FieldAndRobots.getInstance().setTeamNumber(FieldAndRobots.BLUE, FieldAndRobots.ONE, 1);
        FieldAndRobots.getInstance().setTeamNumber(FieldAndRobots.BLUE, FieldAndRobots.TWO, 2);
        FieldAndRobots.getInstance().setTeamNumber(FieldAndRobots.BLUE, FieldAndRobots.THREE, 3);
    }

    /**
     * Gets the UI container for the team in the first station on the Blue
     * alliance.
     *
     * @return The "Blue_UI_Block" container for a team's UI elements.
     */
    public Blue_UI_Block getBlue1() {
        return blue_UI_Block1;
    }

    /**
     * Gets the UI container for the team in the second station on the Blue
     * alliance.
     *
     * @return The "Blue_UI_Block" container for a team's UI elements.
     */
    public Blue_UI_Block getBlue2() {
        return blue_UI_Block2;
    }

    /**
     * Gets the UI container for the team in the third station on the Blue
     * alliance.
     *
     * @return The "Blue_UI_Block" container for a team's UI elements.
     */
    public Blue_UI_Block getBlue3() {
        return blue_UI_Block3;
    }

    /**
     * Gets the Blue Alliance "Ready for match" indicator.
     *
     * @return A JLabel acting as the Blue alliance "Ready for match" indicator.
     */
    public JLabel getBlueIndic() {
        return blueIndic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blue_UI_Block1 = new UI.BlueAlliance.Blue_UI_Block();
        blue_UI_Block2 = new UI.BlueAlliance.Blue_UI_Block();
        blue_UI_Block3 = new UI.BlueAlliance.Blue_UI_Block();
        blueIndic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        setMaximumSize(new java.awt.Dimension(268, 269));
        setMinimumSize(new java.awt.Dimension(268, 269));
        setPreferredSize(new java.awt.Dimension(268, 269));

        blueIndic.setBackground(new java.awt.Color(153, 153, 153));
        blueIndic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blueIndic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blueIndic.setText(" Blue Alliance ");
        blueIndic.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blue_UI_Block1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(blue_UI_Block2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(blue_UI_Block3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(blueIndic, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blueIndic)
                .addGap(1, 1, 1)
                .addComponent(blue_UI_Block1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(blue_UI_Block2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(blue_UI_Block3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blueIndic;
    private UI.BlueAlliance.Blue_UI_Block blue_UI_Block1;
    private UI.BlueAlliance.Blue_UI_Block blue_UI_Block2;
    private UI.BlueAlliance.Blue_UI_Block blue_UI_Block3;
    // End of variables declaration//GEN-END:variables
}
