package UI;

import OFMS.FieldAndRobots;
import OFMS.Main;
import java.awt.Color;

/**
 * This represents a debugging ESTOP testing panel. It is used to test that,
 * internally, the ESTOP command is working for each team.
 *
 * Complete System developed by:
 *
 * @author Alex Bassett
 * @author Walton Robotics - Team 2974
 * @author Foundation code developed by Josh, Andrew Lobos, Team 225
 * @author Structural assistance and refactoring by Doug Neumann
 */
public class ESTOP_Panel extends javax.swing.JPanel {

    /**
     * Holds local reference to Blue index
     */
    private final int BLUE = FieldAndRobots.BLUE;
    /**
     * Holds local reference to Red index
     */
    private final int RED = FieldAndRobots.RED;
    /**
     * Holds local reference to One index
     */
    private final static int ONE = FieldAndRobots.ONE;
    /**
     * Holds local reference to Two index
     */
    private final static int TWO = FieldAndRobots.TWO;
    /**
     * Holds local reference to Three index
     */
    private final static int THREE = FieldAndRobots.THREE;

    /**
     * Creates a new ESTOP_Panel
     */
    public ESTOP_Panel() {
        initComponents();
    }

    /**
     * Called to tell the panel that it needs to update the team numbers that it
     * has inside of it.
     */
    public void updatePanel() {
        String[][] field;
        if (Main.layer != null) {
            field = FieldAndRobots.getInstance().getRedBlueNumbers();
        } else {
            /*
             JOptionPane.showMessageDialog(OFMS_Main.fmsUi,
             "ESTOP panel not declared correctly.",
             "ESTOP setup error",
             JOptionPane.ERROR_MESSAGE);
             */
            field = new String[][]{{"0000", "0000", "0000"}, {"0000", "0000", "0000"}};
        }
        String[] red = field[0];
        String[] blue = field[1];

        R1_Number.setText(red[0]);
        R2_Number.setText(red[1]);
        R3_Number.setText(red[2]);

        B1_Number.setText(blue[0]);
        B2_Number.setText(blue[1]);
        B3_Number.setText(blue[2]);
    }

    //<editor-fold defaultstate="collapsed" desc="IO Status Color Setters">
    /**
     * Sets the communication status of the Red IO Status Block by setting
     * color.
     *
     * @param setColor The new color to set it to.
     */
    public void setRedIOStatus(Color setColor) {
        redIOConnectionIndicator.setBackground(setColor);
    }

    /**
     * Sets the communication status of the Blue IO Status Block by setting
     * color.
     *
     * @param setColor The new color it is set to.
     */
    public void setBlueIOStatus(Color setColor) {
        blueIOConnectionIndicator.setBackground(setColor);
    }
    //</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        B1_Number = new javax.swing.JLabel();
        B2_Number = new javax.swing.JLabel();
        B3_Number = new javax.swing.JLabel();
        B1_ESTOP = new javax.swing.JButton();
        B2_ESTOP = new javax.swing.JButton();
        B3_ESTOP = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        R1_Number = new javax.swing.JLabel();
        R2_Number = new javax.swing.JLabel();
        R3_Number = new javax.swing.JLabel();
        R1_ESTOP = new javax.swing.JButton();
        R2_ESTOP = new javax.swing.JButton();
        R3_ESTOP = new javax.swing.JButton();
        blueIOConnectionIndicator = new javax.swing.JLabel();
        redIOConnectionIndicator = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Blue Teams");

        B1_Number.setBackground(new java.awt.Color(255, 255, 255));
        B1_Number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B1_Number.setText("0000");
        B1_Number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B1_Number.setOpaque(true);

        B2_Number.setBackground(new java.awt.Color(255, 255, 255));
        B2_Number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B2_Number.setText("0001");
        B2_Number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B2_Number.setOpaque(true);

        B3_Number.setBackground(new java.awt.Color(255, 255, 255));
        B3_Number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B3_Number.setText("0002");
        B3_Number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B3_Number.setOpaque(true);

        B1_ESTOP.setText("ESTOP");
        B1_ESTOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1_ESTOPActionPerformed(evt);
            }
        });

        B2_ESTOP.setText("ESTOP");
        B2_ESTOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2_ESTOPActionPerformed(evt);
            }
        });

        B3_ESTOP.setText("ESTOP");
        B3_ESTOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3_ESTOPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(B1_Number)
                        .addGap(18, 18, 18)
                        .addComponent(B1_ESTOP))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(B2_Number)
                        .addGap(18, 18, 18)
                        .addComponent(B2_ESTOP))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(B3_Number)
                        .addGap(18, 18, 18)
                        .addComponent(B3_ESTOP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1_Number)
                    .addComponent(B1_ESTOP))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B2_Number)
                    .addComponent(B2_ESTOP))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B3_Number)
                    .addComponent(B3_ESTOP))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Red Teams");

        R1_Number.setBackground(new java.awt.Color(255, 255, 255));
        R1_Number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        R1_Number.setText("0003");
        R1_Number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R1_Number.setOpaque(true);

        R2_Number.setBackground(new java.awt.Color(255, 255, 255));
        R2_Number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        R2_Number.setText("0004");
        R2_Number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R2_Number.setOpaque(true);

        R3_Number.setBackground(new java.awt.Color(255, 255, 255));
        R3_Number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        R3_Number.setText("0005");
        R3_Number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R3_Number.setOpaque(true);

        R1_ESTOP.setText("ESTOP");
        R1_ESTOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1_ESTOPActionPerformed(evt);
            }
        });

        R2_ESTOP.setText("ESTOP");
        R2_ESTOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2_ESTOPActionPerformed(evt);
            }
        });

        R3_ESTOP.setText("ESTOP");
        R3_ESTOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3_ESTOPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(R1_Number)
                        .addGap(18, 18, 18)
                        .addComponent(R1_ESTOP))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(R2_Number)
                        .addGap(18, 18, 18)
                        .addComponent(R2_ESTOP))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(R3_Number)
                        .addGap(18, 18, 18)
                        .addComponent(R3_ESTOP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1_Number)
                    .addComponent(R1_ESTOP))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2_Number)
                    .addComponent(R2_ESTOP))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R3_Number)
                    .addComponent(R3_ESTOP))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        blueIOConnectionIndicator.setBackground(new java.awt.Color(102, 102, 102));
        blueIOConnectionIndicator.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        blueIOConnectionIndicator.setText("BLUE IO RACK STATUS");
        blueIOConnectionIndicator.setOpaque(true);

        redIOConnectionIndicator.setBackground(new java.awt.Color(102, 102, 102));
        redIOConnectionIndicator.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        redIOConnectionIndicator.setText("RED IO RACK STATUS");
        redIOConnectionIndicator.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueIOConnectionIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redIOConnectionIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueIOConnectionIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redIOConnectionIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Blue Side ESTOPS">
    private void B1_ESTOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1_ESTOPActionPerformed
        // TODO add your handling code here:
        FieldAndRobots.getInstance().actOnRobot(BLUE, ONE,
                FieldAndRobots.SpecialState.ESTOP_ROBOT);
    }//GEN-LAST:event_B1_ESTOPActionPerformed

    private void B2_ESTOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2_ESTOPActionPerformed
        // TODO add your handling code here:
        FieldAndRobots.getInstance().actOnRobot(BLUE, TWO,
                FieldAndRobots.SpecialState.ESTOP_ROBOT);
    }//GEN-LAST:event_B2_ESTOPActionPerformed

    private void B3_ESTOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3_ESTOPActionPerformed
        // TODO add your handling code here:
        FieldAndRobots.getInstance().actOnRobot(BLUE, THREE,
                FieldAndRobots.SpecialState.ESTOP_ROBOT);
    }//GEN-LAST:event_B3_ESTOPActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Red Side ESTOPS">
    private void R1_ESTOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1_ESTOPActionPerformed
        // TODO add your handling code here:
        FieldAndRobots.getInstance().actOnRobot(RED, ONE,
                FieldAndRobots.SpecialState.ESTOP_ROBOT);
    }//GEN-LAST:event_R1_ESTOPActionPerformed

    private void R2_ESTOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2_ESTOPActionPerformed
        // TODO add your handling code here:
        FieldAndRobots.getInstance().actOnRobot(RED, TWO,
                FieldAndRobots.SpecialState.ESTOP_ROBOT);
    }//GEN-LAST:event_R2_ESTOPActionPerformed

    private void R3_ESTOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3_ESTOPActionPerformed
        // TODO add your handling code here:
        FieldAndRobots.getInstance().actOnRobot(RED, THREE,
                FieldAndRobots.SpecialState.ESTOP_ROBOT);
    }//GEN-LAST:event_R3_ESTOPActionPerformed
    //</editor-fold>
    //
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1_ESTOP;
    private javax.swing.JLabel B1_Number;
    private javax.swing.JButton B2_ESTOP;
    private javax.swing.JLabel B2_Number;
    private javax.swing.JButton B3_ESTOP;
    private javax.swing.JLabel B3_Number;
    private javax.swing.JButton R1_ESTOP;
    private javax.swing.JLabel R1_Number;
    private javax.swing.JButton R2_ESTOP;
    private javax.swing.JLabel R2_Number;
    private javax.swing.JButton R3_ESTOP;
    private javax.swing.JLabel R3_Number;
    private javax.swing.JLabel blueIOConnectionIndicator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel redIOConnectionIndicator;
    // End of variables declaration//GEN-END:variables
}
