/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package splashscreen;

/**
 *
 * @author Alex
 */
public class LogoPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogoPanel
     */
    public LogoPanel() {
        initComponents();
        //setBounds(0, 0, WIDTH, HEIGHT);
    }

    public int getLogoHeight() {
        System.out.println("Height: " + jLabel1.getIcon().getIconHeight());// getHeight());
        int height = jLabel1.getIcon().getIconHeight() + jLabel2.getIcon().getIconHeight();
        return  height;
    }

    public int getLogoWidth() {
        System.out.println("Width: " + jLabel1.getIcon().getIconWidth());
        int width = jLabel1.getIcon().getIconWidth();// + jLabel2.getIcon().getIconWidth();
        return  width;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setEnabled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OFMS/LogoFiles/O!FMS DE Logo (Custom).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OFMS/LogoFiles/adc_logo_241x209.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
