package UI.RedAlliance;

import OFMS.FieldAndRobots;
import PLC_Aux.PLC_Sender;
import javax.swing.JLabel;

/**
 * This acts as a container class for 3 team UI containers and an "alliance
 * ready" indicator.
 *
 * Complete System developed by:
 *
 * @author Alex Bassett
 * @author Walton Robotics - Team 2974
 * @author Foundation code developed by Josh, Andrew Lobos, Team 225
 * @author Structural assistance and refactoring by Doug Neumann
 */
public class RedAlli extends javax.swing.JPanel {

    /**
     * Creates a new RedAlli
     */
    public RedAlli() {
        initComponents();
        red_UI_Block1.getTeamIndic().setText("0004");
        red_UI_Block2.getTeamIndic().setText("0005");
        red_UI_Block3.getTeamIndic().setText("0006");
        FieldAndRobots.getInstance().setTeamNumber(FieldAndRobots.RED, FieldAndRobots.ONE, 4);
        FieldAndRobots.getInstance().setTeamNumber(FieldAndRobots.RED, FieldAndRobots.TWO, 5);
        FieldAndRobots.getInstance().setTeamNumber(FieldAndRobots.RED, FieldAndRobots.THREE, 6);
        PLC_Sender.getInstance().updatePLC_TeamNum(true);
    }

    /**
     * Gets the UI container for the team in the first station on the Red
     * alliance.
     *
     * @return The "Red_UI_Block" container for a team's UI elements.
     */
    public Red_UI_Block get1() {
        return red_UI_Block1;
    }

    /**
     * Gets the UI container for the team in the second station on the Red
     * alliance.
     *
     * @return The "Red_UI_Block" container for a team's UI elements.
     */
    public Red_UI_Block get2() {
        return red_UI_Block2;
    }

    /**
     * Gets the UI container for the team in the third station on the Red
     * alliance.
     *
     * @return The "Red_UI_Block" container for a team's UI elements.
     */
    public Red_UI_Block get3() {
        return red_UI_Block3;
    }

    /**
     * Gets the Red Alliance "Ready for match" indicator.
     *
     * @return A JLabel acting as the Red alliance "Ready for match" indicator.
     */
    public JLabel getRedIndic() {
        return redIndic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        red_UI_Block1 = new UI.RedAlliance.Red_UI_Block();
        red_UI_Block2 = new UI.RedAlliance.Red_UI_Block();
        red_UI_Block3 = new UI.RedAlliance.Red_UI_Block();
        redIndic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 0, 0));
        setMaximumSize(new java.awt.Dimension(268, 269));
        setMinimumSize(new java.awt.Dimension(268, 269));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(268, 269));

        redIndic.setBackground(new java.awt.Color(153, 153, 153));
        redIndic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        redIndic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redIndic.setText(" Red Alliance ");
        redIndic.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(red_UI_Block1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(red_UI_Block2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(red_UI_Block3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redIndic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(redIndic)
                .addGap(1, 1, 1)
                .addComponent(red_UI_Block1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(red_UI_Block2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(red_UI_Block3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel redIndic;
    private UI.RedAlliance.Red_UI_Block red_UI_Block1;
    private UI.RedAlliance.Red_UI_Block red_UI_Block2;
    private UI.RedAlliance.Red_UI_Block red_UI_Block3;
    // End of variables declaration//GEN-END:variables
}
